### ISSUE TITLE
Database migration error when setting up for the first time on Windows docker desktop

### ISSUE THREAD

**Issue by PlastMan420** [OPSnet/Gazelle#163]
### steps to recreate
* enable WSL2 on Windows 10
* install docker desktop. use the WSL2 backend
* clone gazelle master branch
* run `docker-compose up`

message:

```
web_1           |  == 20180104060449 Tables: migrating
web_1           | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1304 FUNCTION binomial_ci already exists in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
web_1           | Stack trace:
web_1           | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec('\nCREATE FUNCTIO...')
web_1           | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\PdoAdapter->execute('\nCREATE FUNCTIO...')
web_1           | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute('\nCREATE FUNCTIO...')
web_1           | #3 /var/www/db/migrations/20180104060449_tables.php(36): Phinx\Migration\AbstractMigration->execute('\nCREATE FUNCTIO...')
web_1           | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): Tables->up()
web_1           | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1           | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1           | #7 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('gazelle', 20210720093846, false)
web_1           | #8 /var/www/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #9 /var/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #10 /var/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #12 /var/www/vendor/symfony/console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #13 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1           | #14 {main}
web_1           | PHINX FAILED TO RUN MIGRATIONS
web_1 exited with code 1
```

**Comment by itismadness** [comment]
Could you try doing:
```
sudo rm -rf .docker/data
docker-compose up
```
and see if that resolves things? It looks like you've got a partially existing DB that's being used, causing the error you see here.

**Comment by PlastMan420** [comment]
> Could you try doing:
> 
> ```
> sudo rm -rf .docker/data
> docker-compose up
> ```
> 
> and see if that resolves things? It looks like you've got a partially existing DB that's being used, causing the error you see here.

now I'm getting this ->
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/desktop/mnt/host/d/repo/Gazelle/.docker/data/sphinxsearch
```

**Comment by itismadness** [comment]
Hm, this is on the latest commit on master? You've not made any changes to the version of mariadb that's being used in the docker-compose network?

Just trying to figure out how you'd see a different result than I am

**Comment by PlastMan420** [comment]
yes. just cloned master a few hours ago. and no no mods were made by me

**Comment by itismadness** [comment]
Weird. This is probably a reason we should condense our migrations down into a single file at some point to make getting started a bit easier..

Could you run `docker-compose logs web` and paste the entire outputting surrounding `phinx` (everything after `Phinx by CakePHP - https://phinx.org`), so I know what migration is crashing for you?

**Comment by PlastMan420** [comment]
Here's the entire thing as I couldnt find that line of text you mentioned.
it always fails at `20180104060449` which is the very first one I believe

```
web_1  | Composer 1.8.4 2019-02-11 10:52:10
web_1  | Loading composer repositories with package information
web_1  | Installing dependencies (including require-dev) from lock file
web_1  | Nothing to install or update
web_1  | Generating autoload files
web_1  | yarn install v1.22.5
web_1  | [1/4] Resolving packages...
web_1  | success Already up-to-date.
web_1  | Done in 1.51s.
web_1  | yarn run v1.22.5
web_1  | $ yarn build
web_1  | $ yarn build:scss && yarn build:previews
web_1  | $ webpack --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
web_1  |  DONE  Compiled successfully in 28406ms7:43:34 PM
web_1  |
web_1  |                                                 Asset       Size  Chunks                   Chunk Names
web_1  |                                            mix.js.map   5.83 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/80char/style.css   25.2 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/80char/style.css.map   34.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/apollostage/style.css   65.6 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/apollostage/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_coffee/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_coffee/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_sunset/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_sunset/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/calendar/style.css  988 bytes     mix  [emitted]        mix
web_1  |           public/static/styles/calendar/style.css.map   1.44 KiB     mix  [emitted] [dev]  mix
web_1  |           public/static/styles/dark_ambient/style.css    712 KiB     mix  [emitted]        mix
web_1  |       public/static/styles/dark_ambient/style.css.map    725 KiB     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/dark_cake/style.css     41 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/dark_cake/style.css.map   47.2 KiB     mix  [emitted] [dev]  mix
web_1  |        public/static/styles/datetime_picker/style.css   8.56 KiB     mix  [emitted]        mix
web_1  |    public/static/styles/datetime_picker/style.css.map   10.6 KiB     mix  [emitted] [dev]  mix
web_1  |                       public/static/styles/global.css   12.8 KiB     mix  [emitted]        mix
web_1  |                   public/static/styles/global.css.map     18 KiB     mix  [emitted] [dev]  mix
web_1  |                   public/static/styles/kuro/style.css   28.9 KiB     mix  [emitted]        mix
web_1  |               public/static/styles/kuro/style.css.map   35.6 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/layer_cake/style.css   40.4 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/layer_cake/style.css.map   46.2 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/linohaze/style.css   62.6 KiB     mix  [emitted]        mix
web_1  |           public/static/styles/linohaze/style.css.map   76.7 KiB     mix  [emitted] [dev]  mix
web_1  |                          public/static/styles/log.css  453 bytes     mix  [emitted]        mix
web_1  |                      public/static/styles/log.css.map  840 bytes     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/minimal_mod_alt.css   28.1 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/minimal_mod_alt.css.map   36.8 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/musicbrainz.css  851 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/musicbrainz.css.map    1.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/post_office/style.css   58.1 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/post_office/style.css.map   66.2 KiB     mix  [emitted] [dev]  mix
web_1  |                public/static/styles/postmod/style.css   23.7 KiB     mix  [emitted]        mix
web_1  |            public/static/styles/postmod/style.css.map   31.6 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/proton/style.css   32.3 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/proton/style.css.map   44.4 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/public/style.css   2.51 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/public/style.css.map   3.65 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/tiles/style.css  871 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/tiles/style.css.map   1.32 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/tooltipster/style.css   6.16 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/tooltipster/style.css.map   7.76 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/xanax_cake/style.css   13.7 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/xanax_cake/style.css.map   19.4 KiB     mix  [emitted] [dev]  mix
web_1  | $ node scripts/render_styles_preview.js
web_1  | Building styles:
web_1  |
web_1  |  -> apollostage
web_1  |  -> apollostage_coffee
web_1  |  -> apollostage_sunset
web_1  |  -> dark_ambient
web_1  |  -> dark_cake
web_1  |  -> kuro
web_1  |  -> layer_cake
web_1  |  -> linohaze
web_1  |  -> post_office
web_1  |  -> postmod
web_1  |  -> proton
web_1  |  -> xanax_cake
web_1  |
web_1  | All style previews built
web_1  | Done in 127.89s.
web_1  | Run migrations...
web_1  | Phinx by CakePHP - https://phinx.org.
web_1  |
web_1  | using config file ./phinx.php
web_1  | using config parser php
web_1  | using migration paths
web_1  |  - /var/www/db/migrations
web_1  | using seed paths
web_1  |  - /var/www/db/seeds
web_1  | warning no environment specified, defaulting to: gazelle
web_1  | using adapter mysql
web_1  | using database gazelle
web_1  | ordering by creation time
web_1  |
web_1  |  == 20180104060449 Tables: migrating
web_1  | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1304 FUNCTION binomial_ci already exists in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
web_1  | Stack trace:
web_1  | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec('\nCREATE FUNCTIO...')
web_1  | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\PdoAdapter->execute('\nCREATE FUNCTIO...')
web_1  | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute('\nCREATE FUNCTIO...')
web_1  | #3 /var/www/db/migrations/20180104060449_tables.php(36): Phinx\Migration\AbstractMigration->execute('\nCREATE FUNCTIO...')
web_1  | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): Tables->up()
web_1  | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1  | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1  | #7 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('gazelle', 20210720093846, false)
web_1  | #8 /var/www/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #9 /var/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #10 /var/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #12 /var/www/vendor/symfony/console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #13 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1  | #14 {main}
web_1  | PHINX FAILED TO RUN MIGRATIONS
web_1  | Composer 1.8.4 2019-02-11 10:52:10
web_1  | Loading composer repositories with package information
web_1  | Installing dependencies (including require-dev) from lock file
web_1  | Nothing to install or update
web_1  | Generating autoload files
web_1  | yarn install v1.22.5
web_1  | [1/4] Resolving packages...
web_1  | success Already up-to-date.
web_1  | Done in 0.90s.
web_1  | yarn run v1.22.5
web_1  | $ yarn build
web_1  | $ yarn build:scss && yarn build:previews
web_1  | $ webpack --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
web_1  |  DONE  Compiled successfully in 25365ms7:53:53 PM
web_1  |
web_1  |                                                 Asset       Size  Chunks                   Chunk Names
web_1  |                                            mix.js.map   5.83 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/80char/style.css   25.2 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/80char/style.css.map   34.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/apollostage/style.css   65.6 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/apollostage/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_coffee/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_coffee/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_sunset/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_sunset/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/calendar/style.css  988 bytes     mix  [emitted]        mix
web_1  |           public/static/styles/calendar/style.css.map   1.44 KiB     mix  [emitted] [dev]  mix
web_1  |           public/static/styles/dark_ambient/style.css    712 KiB     mix  [emitted]        mix
web_1  |       public/static/styles/dark_ambient/style.css.map    725 KiB     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/dark_cake/style.css     41 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/dark_cake/style.css.map   47.2 KiB     mix  [emitted] [dev]  mix
web_1  |        public/static/styles/datetime_picker/style.css   8.56 KiB     mix  [emitted]        mix
web_1  |    public/static/styles/datetime_picker/style.css.map   10.6 KiB     mix  [emitted] [dev]  mix
web_1  |                       public/static/styles/global.css   12.8 KiB     mix  [emitted]        mix
web_1  |                   public/static/styles/global.css.map     18 KiB     mix  [emitted] [dev]  mix
web_1  |                   public/static/styles/kuro/style.css   28.9 KiB     mix  [emitted]        mix
web_1  |               public/static/styles/kuro/style.css.map   35.6 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/layer_cake/style.css   40.4 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/layer_cake/style.css.map   46.2 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/linohaze/style.css   62.6 KiB     mix  [emitted]        mix
web_1  |           public/static/styles/linohaze/style.css.map   76.7 KiB     mix  [emitted] [dev]  mix
web_1  |                          public/static/styles/log.css  453 bytes     mix  [emitted]        mix
web_1  |                      public/static/styles/log.css.map  840 bytes     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/minimal_mod_alt.css   28.1 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/minimal_mod_alt.css.map   36.8 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/musicbrainz.css  851 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/musicbrainz.css.map    1.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/post_office/style.css   58.1 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/post_office/style.css.map   66.2 KiB     mix  [emitted] [dev]  mix
web_1  |                public/static/styles/postmod/style.css   23.7 KiB     mix  [emitted]        mix
web_1  |            public/static/styles/postmod/style.css.map   31.6 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/proton/style.css   32.3 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/proton/style.css.map   44.4 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/public/style.css   2.51 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/public/style.css.map   3.65 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/tiles/style.css  871 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/tiles/style.css.map   1.32 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/tooltipster/style.css   6.16 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/tooltipster/style.css.map   7.76 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/xanax_cake/style.css   13.7 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/xanax_cake/style.css.map   19.4 KiB     mix  [emitted] [dev]  mix
web_1  | $ node scripts/render_styles_preview.js
web_1  | Building styles:
web_1  |
web_1  |  -> apollostage
web_1  |  -> apollostage_coffee
web_1  |  -> apollostage_sunset
web_1  |  -> dark_ambient
web_1  |  -> dark_cake
web_1  |  -> kuro
web_1  |  -> layer_cake
web_1  |  -> linohaze
web_1  |  -> post_office
web_1  |  -> postmod
web_1  |  -> proton
web_1  |  -> xanax_cake
web_1  |
web_1  | All style previews built
web_1  | Done in 104.81s.
web_1  | Run migrations...
web_1  | Phinx by CakePHP - https://phinx.org.
web_1  |
web_1  | using config file ./phinx.php
web_1  | using config parser php
web_1  | using migration paths
web_1  |  - /var/www/db/migrations
web_1  | using seed paths
web_1  |  - /var/www/db/seeds
web_1  | warning no environment specified, defaulting to: gazelle
web_1  | using adapter mysql
web_1  | using database gazelle
web_1  | ordering by creation time
web_1  |
web_1  |  == 20180104060449 Tables: migrating
web_1  | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1304 FUNCTION binomial_ci already exists in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
web_1  | Stack trace:
web_1  | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec('\nCREATE FUNCTIO...')
web_1  | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\PdoAdapter->execute('\nCREATE FUNCTIO...')
web_1  | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute('\nCREATE FUNCTIO...')
web_1  | #3 /var/www/db/migrations/20180104060449_tables.php(36): Phinx\Migration\AbstractMigration->execute('\nCREATE FUNCTIO...')
web_1  | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): Tables->up()
web_1  | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1  | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1  | #7 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('gazelle', 20210720093846, false)
web_1  | #8 /var/www/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #9 /var/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #10 /var/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #12 /var/www/vendor/symfony/console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #13 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1  | #14 {main}
web_1  | PHINX FAILED TO RUN MIGRATIONS
web_1  | Composer 1.8.4 2019-02-11 10:52:10
web_1  | Loading composer repositories with package information
web_1  | Installing dependencies (including require-dev) from lock file
web_1  | Nothing to install or update
web_1  | Generating autoload files
web_1  | yarn install v1.22.5
web_1  | [1/4] Resolving packages...
web_1  | success Already up-to-date.
web_1  | Done in 1.72s.
web_1  | yarn run v1.22.5
web_1  | $ yarn build
web_1  | $ yarn build:scss && yarn build:previews
web_1  | $ webpack --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
web_1  |  DONE  Compiled successfully in 29624ms11:49:59 PM
web_1  |
web_1  |                                                 Asset       Size  Chunks                   Chunk Names
web_1  |                                            mix.js.map   5.83 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/80char/style.css   25.2 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/80char/style.css.map   34.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/apollostage/style.css   65.6 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/apollostage/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_coffee/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_coffee/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_sunset/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_sunset/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/calendar/style.css  988 bytes     mix  [emitted]        mix
web_1  |           public/static/styles/calendar/style.css.map   1.44 KiB     mix  [emitted] [dev]  mix
web_1  |           public/static/styles/dark_ambient/style.css    712 KiB     mix  [emitted]        mix
web_1  |       public/static/styles/dark_ambient/style.css.map    725 KiB     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/dark_cake/style.css     41 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/dark_cake/style.css.map   47.2 KiB     mix  [emitted] [dev]  mix
web_1  |        public/static/styles/datetime_picker/style.css   8.56 KiB     mix  [emitted]        mix
web_1  |    public/static/styles/datetime_picker/style.css.map   10.6 KiB     mix  [emitted] [dev]  mix
web_1  |                       public/static/styles/global.css   12.8 KiB     mix  [emitted]        mix
web_1  |                   public/static/styles/global.css.map     18 KiB     mix  [emitted] [dev]  mix
web_1  |                   public/static/styles/kuro/style.css   28.9 KiB     mix  [emitted]        mix
web_1  |               public/static/styles/kuro/style.css.map   35.6 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/layer_cake/style.css   40.4 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/layer_cake/style.css.map   46.2 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/linohaze/style.css   62.6 KiB     mix  [emitted]        mix
web_1  |           public/static/styles/linohaze/style.css.map   76.7 KiB     mix  [emitted] [dev]  mix
web_1  |                          public/static/styles/log.css  453 bytes     mix  [emitted]        mix
web_1  |                      public/static/styles/log.css.map  840 bytes     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/minimal_mod_alt.css   28.1 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/minimal_mod_alt.css.map   36.8 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/musicbrainz.css  851 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/musicbrainz.css.map    1.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/post_office/style.css   58.1 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/post_office/style.css.map   66.2 KiB     mix  [emitted] [dev]  mix
web_1  |                public/static/styles/postmod/style.css   23.7 KiB     mix  [emitted]        mix
web_1  |            public/static/styles/postmod/style.css.map   31.6 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/proton/style.css   32.3 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/proton/style.css.map   44.4 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/public/style.css   2.51 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/public/style.css.map   3.65 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/tiles/style.css  871 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/tiles/style.css.map   1.32 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/tooltipster/style.css   6.16 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/tooltipster/style.css.map   7.76 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/xanax_cake/style.css   13.7 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/xanax_cake/style.css.map   19.4 KiB     mix  [emitted] [dev]  mix
web_1  | $ node scripts/render_styles_preview.js
web_1  | Building styles:
web_1  |
web_1  |  -> apollostage
web_1  |  -> apollostage_coffee
web_1  |  -> apollostage_sunset
web_1  |  -> dark_ambient
web_1  |  -> dark_cake
web_1  |  -> kuro
web_1  |  -> layer_cake
web_1  |  -> linohaze
web_1  |  -> post_office
web_1  |  -> postmod
web_1  |  -> proton
web_1  |  -> xanax_cake
web_1  |
web_1  | All style previews built
web_1  | Done in 150.38s.
web_1  | Run migrations...
web_1  | Phinx by CakePHP - https://phinx.org.
web_1  |
web_1  | using config file ./phinx.php
web_1  | using config parser php
web_1  | using migration paths
web_1  |  - /var/www/db/migrations
web_1  | using seed paths
web_1  |  - /var/www/db/seeds
web_1  | warning no environment specified, defaulting to: gazelle
web_1  | using adapter mysql
web_1  | using database gazelle
web_1  | ordering by creation time
web_1  |
web_1  |  == 20180104060449 Tables: migrating
web_1  | PDOException: SQLSTATE[HY000]: General error: 1364 Field 'LastPostTime' doesn't have a default value in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:326
web_1  | Stack trace:
web_1  | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(326): PDOStatement->execute(Array)
web_1  | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(180): Phinx\Db\Adapter\PdoAdapter->bulkinsert(Object(Phinx\Db\Table\Table), Array)
web_1  | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(103): Phinx\Db\Adapter\AdapterWrapper->bulkinsert(Object(Phinx\Db\Table\Table), Array)
web_1  | #3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(658): Phinx\Db\Adapter\TimedOutputAdapter->bulkinsert(Object(Phinx\Db\Table\Table), Array)
web_1  | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(630): Phinx\Db\Table->saveData()
web_1  | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(688): Phinx\Db\Table->update()
web_1  | #6 /var/www/db/migrations/20180104060449_tables.php(8143): Phinx\Db\Table->save()
web_1  | #7 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): Tables->up()
web_1  | #8 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1  | #9 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1  | #10 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('gazelle', 20210720093846, false)
web_1  | #11 /var/www/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #12 /var/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #13 /var/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #14 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #15 /var/www/vendor/symfony/console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #16 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1  | #17 {main}
web_1  | PHINX FAILED TO RUN MIGRATIONS
web_1  | Composer 1.8.4 2019-02-11 10:52:10
web_1  | Loading composer repositories with package information
web_1  | Installing dependencies (including require-dev) from lock file
web_1  | Nothing to install or update
web_1  | Generating autoload files
web_1  | yarn install v1.22.5
web_1  | [1/4] Resolving packages...
web_1  | success Already up-to-date.
web_1  | Done in 1.44s.
web_1  | yarn run v1.22.5
web_1  | $ yarn build
web_1  | $ yarn build:scss && yarn build:previews
web_1  | $ webpack --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
web_1  |  DONE  Compiled successfully in 36126ms12:12:21 AM
web_1  |
web_1  |                                                 Asset       Size  Chunks                   Chunk Names
web_1  |                                            mix.js.map   5.83 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/80char/style.css   25.2 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/80char/style.css.map   34.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/apollostage/style.css   65.6 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/apollostage/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_coffee/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_coffee/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |     public/static/styles/apollostage_sunset/style.css   65.6 KiB     mix  [emitted]        mix
web_1  | public/static/styles/apollostage_sunset/style.css.map    151 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/calendar/style.css  988 bytes     mix  [emitted]        mix
web_1  |           public/static/styles/calendar/style.css.map   1.44 KiB     mix  [emitted] [dev]  mix
web_1  |           public/static/styles/dark_ambient/style.css    712 KiB     mix  [emitted]        mix
web_1  |       public/static/styles/dark_ambient/style.css.map    725 KiB     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/dark_cake/style.css     41 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/dark_cake/style.css.map   47.2 KiB     mix  [emitted] [dev]  mix
web_1  |        public/static/styles/datetime_picker/style.css   8.56 KiB     mix  [emitted]        mix
web_1  |    public/static/styles/datetime_picker/style.css.map   10.6 KiB     mix  [emitted] [dev]  mix
web_1  |                       public/static/styles/global.css   12.8 KiB     mix  [emitted]        mix
web_1  |                   public/static/styles/global.css.map     18 KiB     mix  [emitted] [dev]  mix
web_1  |                   public/static/styles/kuro/style.css   28.9 KiB     mix  [emitted]        mix
web_1  |               public/static/styles/kuro/style.css.map   35.6 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/layer_cake/style.css   40.4 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/layer_cake/style.css.map   46.2 KiB     mix  [emitted] [dev]  mix
web_1  |               public/static/styles/linohaze/style.css   62.6 KiB     mix  [emitted]        mix
web_1  |           public/static/styles/linohaze/style.css.map   76.7 KiB     mix  [emitted] [dev]  mix
web_1  |                          public/static/styles/log.css  453 bytes     mix  [emitted]        mix
web_1  |                      public/static/styles/log.css.map  840 bytes     mix  [emitted] [dev]  mix
web_1  |              public/static/styles/minimal_mod_alt.css   28.1 KiB     mix  [emitted]        mix
web_1  |          public/static/styles/minimal_mod_alt.css.map   36.8 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/musicbrainz.css  851 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/musicbrainz.css.map    1.3 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/post_office/style.css   58.1 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/post_office/style.css.map   66.2 KiB     mix  [emitted] [dev]  mix
web_1  |                public/static/styles/postmod/style.css   23.7 KiB     mix  [emitted]        mix
web_1  |            public/static/styles/postmod/style.css.map   31.6 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/proton/style.css   32.3 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/proton/style.css.map   44.4 KiB     mix  [emitted] [dev]  mix
web_1  |                 public/static/styles/public/style.css   2.51 KiB     mix  [emitted]        mix
web_1  |             public/static/styles/public/style.css.map   3.65 KiB     mix  [emitted] [dev]  mix
web_1  |                  public/static/styles/tiles/style.css  871 bytes     mix  [emitted]        mix
web_1  |              public/static/styles/tiles/style.css.map   1.32 KiB     mix  [emitted] [dev]  mix
web_1  |            public/static/styles/tooltipster/style.css   6.16 KiB     mix  [emitted]        mix
web_1  |        public/static/styles/tooltipster/style.css.map   7.76 KiB     mix  [emitted] [dev]  mix
web_1  |             public/static/styles/xanax_cake/style.css   13.7 KiB     mix  [emitted]        mix
web_1  |         public/static/styles/xanax_cake/style.css.map   19.4 KiB     mix  [emitted] [dev]  mix
web_1  | $ node scripts/render_styles_preview.js
web_1  | Building styles:
web_1  |
web_1  |  -> apollostage
web_1  |  -> apollostage_coffee
web_1  |  -> apollostage_sunset
web_1  |  -> dark_ambient
web_1  |  -> dark_cake
web_1  |  -> kuro
web_1  |  -> layer_cake
web_1  |  -> linohaze
web_1  |  -> post_office
web_1  |  -> postmod
web_1  |  -> proton
web_1  |  -> xanax_cake
web_1  |
web_1  | All style previews built
web_1  | Done in 179.20s.
web_1  | Run migrations...
web_1  | Phinx by CakePHP - https://phinx.org.
web_1  |
web_1  | using config file ./phinx.php
web_1  | using config parser php
web_1  | using migration paths
web_1  |  - /var/www/db/migrations
web_1  | using seed paths
web_1  |  - /var/www/db/seeds
web_1  | warning no environment specified, defaulting to: gazelle
web_1  | using adapter mysql
web_1  | using database gazelle
web_1  | ordering by creation time
web_1  |
web_1  |  == 20180104060449 Tables: migrating
web_1  | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1304 FUNCTION binomial_ci already exists in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
web_1  | Stack trace:
web_1  | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec('\nCREATE FUNCTIO...')
web_1  | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(156): Phinx\Db\Adapter\PdoAdapter->execute('\nCREATE FUNCTIO...')
web_1  | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(198): Phinx\Db\Adapter\AdapterWrapper->execute('\nCREATE FUNCTIO...')
web_1  | #3 /var/www/db/migrations/20180104060449_tables.php(36): Phinx\Migration\AbstractMigration->execute('\nCREATE FUNCTIO...')
web_1  | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): Tables->up()
web_1  | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1  | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1  | #7 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('gazelle', 20210720093846, false)
web_1  | #8 /var/www/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #9 /var/www/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #10 /var/www/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #12 /var/www/vendor/symfony/console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1  | #13 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1  | #14 {main}
web_1  | PHINX FAILED TO RUN MIGRATIONS
```

**Comment by PlastMan420** [comment]
okay I've made that text block shorter. I've found that line you mentioned. there are 3 blocks for the samething and they all fail at the first migration.

**Comment by itismadness** [comment]
I've pushed a commit to master that I think should resolve this particular problem, but there might be more.

You'll need to wipe the `.docker/data/mysql` directory and start fresh with the DB.

**Comment by PlastMan420** [comment]
okay done. but now it shows this
```
[+] Running 0/1
 - ocelot Error
Error response from daemon: pull access denied for ocelot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by PlastMan420** [comment]
Okay so I have followed the new docs with ocelot. migrations had succeeeded. but now it failed to seed the db.

```
...
web_1           |  == 20210720093846 UsersHistoryEmailUseragent: migrating
web_1           |  == 20210720093846 UsersHistoryEmailUseragent: migrated 0.5033s
web_1           |
web_1           | All Done. Took 234.8044s
web_1           |
web_1           |
web_1           | Run seed:run...
web_1           | Phinx by CakePHP - https://phinx.org.
web_1           |
web_1           | using config file ./phinx.php
web_1           | using config parser php
web_1           | using migration paths
web_1           |  - /var/www/db/migrations
web_1           | using seed paths
web_1           |  - /var/www/db/seeds
web_1           | warning no environment specified, defaulting to: gazelle
web_1           | using adapter mysql
web_1           | using database gazelle
web_1           |
web_1           |  == InitialUserSeeder: seeding
web_1           |
web_1           | PHINX FAILED TO SEED
web_1           | In PdoAdapter.php line 326:
web_1           |
web_1           |   SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'n
web_1           |   ow()' for column `gazelle`.`user_last_access`.`last_access` at row 1
web_1           |
web_1           |
web_1           | seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]
web_1           |
web_1 exited with code 1
```

**Comment by PlastMan420** [comment]
Hello again. I have been looking around entrypoint.sh for a bit and attached to the projects container and found that it's using php7.3. while you set it to use php8 in dockerfile. it has been outputting an error about `php8.0-fpm` service not being found. and apparently it had `php7.3-fpm` instead.
so imo you might need to upgrade from debian-buster to debian-sid or anything else if you want to use more recent php

**Comment by itismadness** [comment]
I've pushed a large number of commits that should hopefully resolve the above stuff, including getting it so that we properly install and run PHP8, amongst various other things:

```
root@9d4e15fec40e:/var/www# apt list | grep php

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

php-apcu/now 5.1.20+4.0.11-1+0~20210304.24+debian10~1.gbp1c3d4d amd64 [installed,local]
php-bcmath/now 2:8.0+84+0~20210621.36+debian10~1.gbp28513e all [installed,local]
php-common/now 2:84+0~20210621.36+debian10~1.gbp28513e all [installed,local]
php-memcached/now 3.1.5+2.2.0-9+0~20210228.30+debian10~1.gbp2db493 amd64 [installed,local]
php-xdebug/now 3.0.4+2.9.8+2.8.1+2.5.5-1+0~20210604.37+debian10~1.gbpf5098c amd64 [installed,local]
php8.0-apcu/now 5.1.20+4.0.11-1+0~20210304.24+debian10~1.gbp1c3d4d amd64 [installed,local]
php8.0-bcmath/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-cli/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-common/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-curl/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-fpm/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-gd/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-igbinary/now 3.2.6+2.0.8-1+0~20210913.27+debian10~1.gbp64b0ea amd64 [installed,local]
php8.0-mbstring/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-memcached/now 3.1.5+2.2.0-9+0~20210228.30+debian10~1.gbp2db493 amd64 [installed,local]
php8.0-msgpack/now 2.1.2+0.5.7-6+0~20210301.28+debian10~1.gbpcc7388 amd64 [installed,local]
php8.0-mysql/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-opcache/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-readline/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-xdebug/now 3.0.4+2.9.8+2.8.1+2.5.5-1+0~20210604.37+debian10~1.gbpf5098c amd64 [installed,local]
php8.0-xml/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0-zip/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd amd64 [installed,local]
php8.0/now 8.0.11-1+0~20210923.24+debian10~1.gbp50d5dd all [installed,local]
```

Doing `docker-compose up` works as expected for me at this time.

**Comment by Robert-Ernst** [comment]
Still the same issue on the very first time run after following the official readme steps.

And I'm running a Ubuntu 20.04.3 LTS. So it's not a windows dependency issue.
Also no general Docker cause since I got plenty of container running without issues.

```web_1           | All style previews built
web_1           | Done in 18.25s.
web_1           | GENERATING GAZELLE CONFIG...
web_1           |
web_1           |
web_1           | Run migrations...
web_1           | Phinx by CakePHP - https://phinx.org.
web_1           |
web_1           | using config file phinx.php
web_1           | using config parser php
web_1           | using migration paths
web_1           |  - /var/www/db/migrations
web_1           | using seed paths
web_1           |  - /var/www/db/seeds
web_1           | warning no environment specified, defaulting to: gazelle
web_1           | using adapter mysql
web_1           | using database gazelle
web_1           | ordering by creation time
web_1           |
web_1           |  == 20180104060449 Tables: migrating
web_1           | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1.844674407371E+19) unsigned NOT NULL DEFAULT '0', `Votes` INT(10) unsigned N...' at line 1 in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192```

**Comment by Robert-Ernst** [comment]
After doing
```
sudo rm -rf .docker/data
docker-compose up
``` 

we get the same error:

```web_1           |  == 20180104060449 Tables: migrating
ocelot_1        | Still waiting for Web (Count: 20).
web_1           | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1.844674407371E+19) unsigned NOT NULL DEFAULT '0', `Votes` INT(10) unsigned N...' at line 1 in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
web_1           | Stack trace:
web_1           | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('CREATE TABLE `s...')
web_1           | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(339): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `s...')
web_1           | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
web_1           | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions(false)
web_1           | #7 /var/www/db/migrations/20180104060449_tables.php(261): Phinx\Db\Table->create()
web_1           | #8 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): Tables->up()
web_1           | #9 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(376): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1           | #10 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1           | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20211206083341, false)
web_1           | #12 /var/www/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #13 /var/www/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #14 /var/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #15 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #16 /var/www/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #17 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1           | #18 {main}
web_1           | PHINX FAILED TO RUN MIGRATIONS
gazelle_web_1 exited with code 1```

**Comment by alexohneander** [comment]
I have the same error as Robert:
```
web_1           | Run migrations...
web_1           | Phinx by CakePHP - https://phinx.org.
web_1           |
web_1           | using config file phinx.php
web_1           | using config parser php
web_1           | using migration paths
web_1           |  - /var/www/db/migrations
web_1           | using seed paths
web_1           |  - /var/www/db/seeds
web_1           | warning no environment specified, defaulting to: gazelle
web_1           | using adapter mysql
web_1           | using database gazelle
web_1           | ordering by creation time
web_1           |
web_1           |  == 20180104060449 Tables: migrating
web_1           | PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1.844674407371E+19) unsigned NOT NULL DEFAULT '0', `Votes` INT(10) unsigned N...' at line 1 in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
web_1           | Stack trace:
web_1           | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('CREATE TABLE `s...')
web_1           | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(339): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `s...')
web_1           | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
web_1           | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
web_1           | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions(false)
web_1           | #7 /var/www/db/migrations/20180104060449_tables.php(261): Phinx\Db\Table->create()
web_1           | #8 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): Tables->up()
web_1           | #9 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(376): Phinx\Migration\Manager\Environment->executeMigration(Object(Tables), 'up', false)
web_1           | #10 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration('gazelle', Object(Tables), 'up', false)
web_1           | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20211206083341, false)
web_1           | #12 /var/www/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #13 /var/www/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #14 /var/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #15 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #16 /var/www/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
web_1           | #17 /var/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
web_1           | #18 {main}
web_1           | PHINX FAILED TO RUN MIGRATIONS
```

**Comment by alexohneander** [comment]
`MysqlAdapter::INT_TINY` 
It's because of the Big & Tiny int. I don't have enough background knowledge why they are set but if you replace them with normal int values, the sql migration can be executed.

**Comment by 3nsam** [comment]
I'm having the same error on Debian 10 (4.19) and Manjaro 21.2.1 (5.10 LTS), the logs are identical.

**Comment by Nirzak** [comment]
Can someone here provide me the fully fixed 20180104060449_tables.php file. Getting migration error because of this file.

**Comment by Nirzak** [comment]
> 

Tried that and it worked! I think it should be also fixed in the master branch of this repository. @itismadness
